// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: proto/lastvisit/lastvisit.proto

package lastvisit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lastvisit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lastvisit *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lastvisit,proto3" json:"lastvisit,omitempty"`
	RoomId    int32                  `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *Lastvisit) Reset() {
	*x = Lastvisit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lastvisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lastvisit) ProtoMessage() {}

func (x *Lastvisit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lastvisit.ProtoReflect.Descriptor instead.
func (*Lastvisit) Descriptor() ([]byte, []int) {
	return file_proto_lastvisit_lastvisit_proto_rawDescGZIP(), []int{0}
}

func (x *Lastvisit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Lastvisit) GetLastvisit() *timestamppb.Timestamp {
	if x != nil {
		return x.Lastvisit
	}
	return nil
}

func (x *Lastvisit) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type FindByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId int32  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *FindByUserIDRequest) Reset() {
	*x = FindByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByUserIDRequest) ProtoMessage() {}

func (x *FindByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lastvisit_lastvisit_proto_rawDescGZIP(), []int{1}
}

func (x *FindByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindByUserIDRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type FindByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lastvisit *Lastvisit `protobuf:"bytes,1,opt,name=lastvisit,proto3" json:"lastvisit,omitempty"`
}

func (x *FindByUserIDResponse) Reset() {
	*x = FindByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByUserIDResponse) ProtoMessage() {}

func (x *FindByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lastvisit_lastvisit_proto_rawDescGZIP(), []int{2}
}

func (x *FindByUserIDResponse) GetLastvisit() *Lastvisit {
	if x != nil {
		return x.Lastvisit
	}
	return nil
}

type UpdateLastvisitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId int32  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *UpdateLastvisitRequest) Reset() {
	*x = UpdateLastvisitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLastvisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastvisitRequest) ProtoMessage() {}

func (x *UpdateLastvisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastvisitRequest.ProtoReflect.Descriptor instead.
func (*UpdateLastvisitRequest) Descriptor() ([]byte, []int) {
	return file_proto_lastvisit_lastvisit_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLastvisitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLastvisitRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type UpdateLastvisitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lastvisit *Lastvisit `protobuf:"bytes,1,opt,name=lastvisit,proto3" json:"lastvisit,omitempty"`
}

func (x *UpdateLastvisitResponse) Reset() {
	*x = UpdateLastvisitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLastvisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastvisitResponse) ProtoMessage() {}

func (x *UpdateLastvisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lastvisit_lastvisit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastvisitResponse.ProtoReflect.Descriptor instead.
func (*UpdateLastvisitResponse) Descriptor() ([]byte, []int) {
	return file_proto_lastvisit_lastvisit_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLastvisitResponse) GetLastvisit() *Lastvisit {
	if x != nil {
		return x.Lastvisit
	}
	return nil
}

var File_proto_lastvisit_lastvisit_proto protoreflect.FileDescriptor

var file_proto_lastvisit_lastvisit_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69,
	0x74, 0x2f, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a,
	0x09, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x4a, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x76,
	0x69, 0x73, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x73,
	0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74,
	0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x22, 0x4a, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69,
	0x74, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x52, 0x09, 0x6c, 0x61, 0x73,
	0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x32, 0xbd, 0x01, 0x0a, 0x10, 0x4c, 0x61, 0x73, 0x74, 0x76,
	0x69, 0x73, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x6c, 0x61,
	0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x61,
	0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x12,
	0x21, 0x2e, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6c, 0x61, 0x73, 0x74, 0x76, 0x69, 0x73, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_lastvisit_lastvisit_proto_rawDescOnce sync.Once
	file_proto_lastvisit_lastvisit_proto_rawDescData = file_proto_lastvisit_lastvisit_proto_rawDesc
)

func file_proto_lastvisit_lastvisit_proto_rawDescGZIP() []byte {
	file_proto_lastvisit_lastvisit_proto_rawDescOnce.Do(func() {
		file_proto_lastvisit_lastvisit_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lastvisit_lastvisit_proto_rawDescData)
	})
	return file_proto_lastvisit_lastvisit_proto_rawDescData
}

var file_proto_lastvisit_lastvisit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_lastvisit_lastvisit_proto_goTypes = []interface{}{
	(*Lastvisit)(nil),               // 0: lastvisit.Lastvisit
	(*FindByUserIDRequest)(nil),     // 1: lastvisit.FindByUserIDRequest
	(*FindByUserIDResponse)(nil),    // 2: lastvisit.FindByUserIDResponse
	(*UpdateLastvisitRequest)(nil),  // 3: lastvisit.UpdateLastvisitRequest
	(*UpdateLastvisitResponse)(nil), // 4: lastvisit.UpdateLastvisitResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_proto_lastvisit_lastvisit_proto_depIdxs = []int32{
	5, // 0: lastvisit.Lastvisit.lastvisit:type_name -> google.protobuf.Timestamp
	0, // 1: lastvisit.FindByUserIDResponse.lastvisit:type_name -> lastvisit.Lastvisit
	0, // 2: lastvisit.UpdateLastvisitResponse.lastvisit:type_name -> lastvisit.Lastvisit
	1, // 3: lastvisit.LastvisitService.FindByUserID:input_type -> lastvisit.FindByUserIDRequest
	3, // 4: lastvisit.LastvisitService.UpdateLastvisit:input_type -> lastvisit.UpdateLastvisitRequest
	2, // 5: lastvisit.LastvisitService.FindByUserID:output_type -> lastvisit.FindByUserIDResponse
	4, // 6: lastvisit.LastvisitService.UpdateLastvisit:output_type -> lastvisit.UpdateLastvisitResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_lastvisit_lastvisit_proto_init() }
func file_proto_lastvisit_lastvisit_proto_init() {
	if File_proto_lastvisit_lastvisit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lastvisit_lastvisit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lastvisit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lastvisit_lastvisit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lastvisit_lastvisit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lastvisit_lastvisit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLastvisitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lastvisit_lastvisit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLastvisitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lastvisit_lastvisit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lastvisit_lastvisit_proto_goTypes,
		DependencyIndexes: file_proto_lastvisit_lastvisit_proto_depIdxs,
		MessageInfos:      file_proto_lastvisit_lastvisit_proto_msgTypes,
	}.Build()
	File_proto_lastvisit_lastvisit_proto = out.File
	file_proto_lastvisit_lastvisit_proto_rawDesc = nil
	file_proto_lastvisit_lastvisit_proto_goTypes = nil
	file_proto_lastvisit_lastvisit_proto_depIdxs = nil
}
