// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.0
// source: proto/message/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (MessageService_ChatClient, error)
	FindAllMessageByRoomID(ctx context.Context, in *FindAllMessageByRoomIDRequest, opts ...grpc.CallOption) (*FindAllMessageByRoomIDResponse, error)
	FindLatestMessageByRoomId(ctx context.Context, in *FindLatestMessageByRoomIdRequest, opts ...grpc.CallOption) (*FIndLastestMessageByRoomIdResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (MessageService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], "/message.MessageService/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceChatClient{stream}
	return x, nil
}

type MessageService_ChatClient interface {
	Send(*ClientEvent) error
	Recv() (*ServerEvent, error)
	grpc.ClientStream
}

type messageServiceChatClient struct {
	grpc.ClientStream
}

func (x *messageServiceChatClient) Send(m *ClientEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceChatClient) Recv() (*ServerEvent, error) {
	m := new(ServerEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageServiceClient) FindAllMessageByRoomID(ctx context.Context, in *FindAllMessageByRoomIDRequest, opts ...grpc.CallOption) (*FindAllMessageByRoomIDResponse, error) {
	out := new(FindAllMessageByRoomIDResponse)
	err := c.cc.Invoke(ctx, "/message.MessageService/FindAllMessageByRoomID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) FindLatestMessageByRoomId(ctx context.Context, in *FindLatestMessageByRoomIdRequest, opts ...grpc.CallOption) (*FIndLastestMessageByRoomIdResponse, error) {
	out := new(FIndLastestMessageByRoomIdResponse)
	err := c.cc.Invoke(ctx, "/message.MessageService/FindLatestMessageByRoomId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	Chat(MessageService_ChatServer) error
	FindAllMessageByRoomID(context.Context, *FindAllMessageByRoomIDRequest) (*FindAllMessageByRoomIDResponse, error)
	FindLatestMessageByRoomId(context.Context, *FindLatestMessageByRoomIdRequest) (*FIndLastestMessageByRoomIdResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) Chat(MessageService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedMessageServiceServer) FindAllMessageByRoomID(context.Context, *FindAllMessageByRoomIDRequest) (*FindAllMessageByRoomIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllMessageByRoomID not implemented")
}
func (UnimplementedMessageServiceServer) FindLatestMessageByRoomId(context.Context, *FindLatestMessageByRoomIdRequest) (*FIndLastestMessageByRoomIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLatestMessageByRoomId not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServiceServer).Chat(&messageServiceChatServer{stream})
}

type MessageService_ChatServer interface {
	Send(*ServerEvent) error
	Recv() (*ClientEvent, error)
	grpc.ServerStream
}

type messageServiceChatServer struct {
	grpc.ServerStream
}

func (x *messageServiceChatServer) Send(m *ServerEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceChatServer) Recv() (*ClientEvent, error) {
	m := new(ClientEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MessageService_FindAllMessageByRoomID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllMessageByRoomIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FindAllMessageByRoomID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/FindAllMessageByRoomID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FindAllMessageByRoomID(ctx, req.(*FindAllMessageByRoomIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_FindLatestMessageByRoomId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLatestMessageByRoomIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FindLatestMessageByRoomId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/FindLatestMessageByRoomId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FindLatestMessageByRoomId(ctx, req.(*FindLatestMessageByRoomIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllMessageByRoomID",
			Handler:    _MessageService_FindAllMessageByRoomID_Handler,
		},
		{
			MethodName: "FindLatestMessageByRoomId",
			Handler:    _MessageService_FindLatestMessageByRoomId_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _MessageService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/message/message.proto",
}
