// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.0
// source: proto/chatroom/chatroom.proto

package chatroom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatroomServiceClient is the client API for ChatroomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatroomServiceClient interface {
	CreateChatroom(ctx context.Context, in *CreateChatroomRequest, opts ...grpc.CallOption) (*CreateChatroomResponse, error)
	FindChatroomByID(ctx context.Context, in *FindChatroomByIDRequest, opts ...grpc.CallOption) (*FindChatroomByIDResponse, error)
	PatchChatroom(ctx context.Context, in *PatchChatroomRequest, opts ...grpc.CallOption) (*PatchChatroomResponse, error)
	DeleteChatroom(ctx context.Context, in *DeleteChatroomRequest, opts ...grpc.CallOption) (*DeleteChatroomResponse, error)
}

type chatroomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatroomServiceClient(cc grpc.ClientConnInterface) ChatroomServiceClient {
	return &chatroomServiceClient{cc}
}

func (c *chatroomServiceClient) CreateChatroom(ctx context.Context, in *CreateChatroomRequest, opts ...grpc.CallOption) (*CreateChatroomResponse, error) {
	out := new(CreateChatroomResponse)
	err := c.cc.Invoke(ctx, "/chatroom.ChatroomService/CreateChatroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) FindChatroomByID(ctx context.Context, in *FindChatroomByIDRequest, opts ...grpc.CallOption) (*FindChatroomByIDResponse, error) {
	out := new(FindChatroomByIDResponse)
	err := c.cc.Invoke(ctx, "/chatroom.ChatroomService/FindChatroomByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) PatchChatroom(ctx context.Context, in *PatchChatroomRequest, opts ...grpc.CallOption) (*PatchChatroomResponse, error) {
	out := new(PatchChatroomResponse)
	err := c.cc.Invoke(ctx, "/chatroom.ChatroomService/PatchChatroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) DeleteChatroom(ctx context.Context, in *DeleteChatroomRequest, opts ...grpc.CallOption) (*DeleteChatroomResponse, error) {
	out := new(DeleteChatroomResponse)
	err := c.cc.Invoke(ctx, "/chatroom.ChatroomService/DeleteChatroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatroomServiceServer is the server API for ChatroomService service.
// All implementations must embed UnimplementedChatroomServiceServer
// for forward compatibility
type ChatroomServiceServer interface {
	CreateChatroom(context.Context, *CreateChatroomRequest) (*CreateChatroomResponse, error)
	FindChatroomByID(context.Context, *FindChatroomByIDRequest) (*FindChatroomByIDResponse, error)
	PatchChatroom(context.Context, *PatchChatroomRequest) (*PatchChatroomResponse, error)
	DeleteChatroom(context.Context, *DeleteChatroomRequest) (*DeleteChatroomResponse, error)
	mustEmbedUnimplementedChatroomServiceServer()
}

// UnimplementedChatroomServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatroomServiceServer struct {
}

func (UnimplementedChatroomServiceServer) CreateChatroom(context.Context, *CreateChatroomRequest) (*CreateChatroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatroom not implemented")
}
func (UnimplementedChatroomServiceServer) FindChatroomByID(context.Context, *FindChatroomByIDRequest) (*FindChatroomByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindChatroomByID not implemented")
}
func (UnimplementedChatroomServiceServer) PatchChatroom(context.Context, *PatchChatroomRequest) (*PatchChatroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchChatroom not implemented")
}
func (UnimplementedChatroomServiceServer) DeleteChatroom(context.Context, *DeleteChatroomRequest) (*DeleteChatroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChatroom not implemented")
}
func (UnimplementedChatroomServiceServer) mustEmbedUnimplementedChatroomServiceServer() {}

// UnsafeChatroomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatroomServiceServer will
// result in compilation errors.
type UnsafeChatroomServiceServer interface {
	mustEmbedUnimplementedChatroomServiceServer()
}

func RegisterChatroomServiceServer(s grpc.ServiceRegistrar, srv ChatroomServiceServer) {
	s.RegisterService(&ChatroomService_ServiceDesc, srv)
}

func _ChatroomService_CreateChatroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).CreateChatroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatroom.ChatroomService/CreateChatroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).CreateChatroom(ctx, req.(*CreateChatroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_FindChatroomByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindChatroomByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).FindChatroomByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatroom.ChatroomService/FindChatroomByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).FindChatroomByID(ctx, req.(*FindChatroomByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_PatchChatroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchChatroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).PatchChatroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatroom.ChatroomService/PatchChatroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).PatchChatroom(ctx, req.(*PatchChatroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_DeleteChatroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).DeleteChatroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatroom.ChatroomService/DeleteChatroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).DeleteChatroom(ctx, req.(*DeleteChatroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatroomService_ServiceDesc is the grpc.ServiceDesc for ChatroomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatroomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatroom.ChatroomService",
	HandlerType: (*ChatroomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChatroom",
			Handler:    _ChatroomService_CreateChatroom_Handler,
		},
		{
			MethodName: "FindChatroomByID",
			Handler:    _ChatroomService_FindChatroomByID_Handler,
		},
		{
			MethodName: "PatchChatroom",
			Handler:    _ChatroomService_PatchChatroom_Handler,
		},
		{
			MethodName: "DeleteChatroom",
			Handler:    _ChatroomService_DeleteChatroom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chatroom/chatroom.proto",
}
