// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: proto/room_invite/room_invite.proto

package room_invite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId     int32                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sender     string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	InviteTo   string                 `protobuf:"bytes,4,opt,name=invite_to,json=inviteTo,proto3" json:"invite_to,omitempty"`
	IsAccepted bool                   `protobuf:"varint,5,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"`
	IsDenied   bool                   `protobuf:"varint,6,opt,name=is_denied,json=isDenied,proto3" json:"is_denied,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *RoomInvite) Reset() {
	*x = RoomInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInvite) ProtoMessage() {}

func (x *RoomInvite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInvite.ProtoReflect.Descriptor instead.
func (*RoomInvite) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{0}
}

func (x *RoomInvite) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomInvite) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInvite) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *RoomInvite) GetInviteTo() string {
	if x != nil {
		return x.InviteTo
	}
	return ""
}

func (x *RoomInvite) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *RoomInvite) GetIsDenied() bool {
	if x != nil {
		return x.IsDenied
	}
	return false
}

func (x *RoomInvite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomInvite) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRoomInviteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int32  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sender     string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	InviteTo   string `protobuf:"bytes,3,opt,name=invite_to,json=inviteTo,proto3" json:"invite_to,omitempty"`
	IsAccepted bool   `protobuf:"varint,4,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"`
	IsDenied   bool   `protobuf:"varint,5,opt,name=is_denied,json=isDenied,proto3" json:"is_denied,omitempty"`
}

func (x *CreateRoomInviteRequest) Reset() {
	*x = CreateRoomInviteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomInviteRequest) ProtoMessage() {}

func (x *CreateRoomInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomInviteRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoomInviteRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *CreateRoomInviteRequest) GetInviteTo() string {
	if x != nil {
		return x.InviteTo
	}
	return ""
}

func (x *CreateRoomInviteRequest) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *CreateRoomInviteRequest) GetIsDenied() bool {
	if x != nil {
		return x.IsDenied
	}
	return false
}

type CreateRoomInviteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invite *RoomInvite `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
}

func (x *CreateRoomInviteResponse) Reset() {
	*x = CreateRoomInviteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomInviteResponse) ProtoMessage() {}

func (x *CreateRoomInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomInviteResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomInviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomInviteResponse) GetInvite() *RoomInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

type FindRoomInviteByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindRoomInviteByIDRequest) Reset() {
	*x = FindRoomInviteByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRoomInviteByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoomInviteByIDRequest) ProtoMessage() {}

func (x *FindRoomInviteByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoomInviteByIDRequest.ProtoReflect.Descriptor instead.
func (*FindRoomInviteByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{3}
}

func (x *FindRoomInviteByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindRoomInviteByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invite *RoomInvite `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
}

func (x *FindRoomInviteByIDResponse) Reset() {
	*x = FindRoomInviteByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRoomInviteByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoomInviteByIDResponse) ProtoMessage() {}

func (x *FindRoomInviteByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoomInviteByIDResponse.ProtoReflect.Descriptor instead.
func (*FindRoomInviteByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{4}
}

func (x *FindRoomInviteByIDResponse) GetInvite() *RoomInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

type FindAllRoomInvitesBySenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *FindAllRoomInvitesBySenderRequest) Reset() {
	*x = FindAllRoomInvitesBySenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllRoomInvitesBySenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoomInvitesBySenderRequest) ProtoMessage() {}

func (x *FindAllRoomInvitesBySenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoomInvitesBySenderRequest.ProtoReflect.Descriptor instead.
func (*FindAllRoomInvitesBySenderRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllRoomInvitesBySenderRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type FindAllRoomInvitesBySenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invites []*RoomInvite `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
}

func (x *FindAllRoomInvitesBySenderResponse) Reset() {
	*x = FindAllRoomInvitesBySenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllRoomInvitesBySenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoomInvitesBySenderResponse) ProtoMessage() {}

func (x *FindAllRoomInvitesBySenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoomInvitesBySenderResponse.ProtoReflect.Descriptor instead.
func (*FindAllRoomInvitesBySenderResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllRoomInvitesBySenderResponse) GetInvites() []*RoomInvite {
	if x != nil {
		return x.Invites
	}
	return nil
}

type FindAllRoomInvitesByRoomIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *FindAllRoomInvitesByRoomIDRequest) Reset() {
	*x = FindAllRoomInvitesByRoomIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllRoomInvitesByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoomInvitesByRoomIDRequest) ProtoMessage() {}

func (x *FindAllRoomInvitesByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoomInvitesByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllRoomInvitesByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllRoomInvitesByRoomIDRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type FindAllRoomInvitesByRoomIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invites []*RoomInvite `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
}

func (x *FindAllRoomInvitesByRoomIDResponse) Reset() {
	*x = FindAllRoomInvitesByRoomIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllRoomInvitesByRoomIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoomInvitesByRoomIDResponse) ProtoMessage() {}

func (x *FindAllRoomInvitesByRoomIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoomInvitesByRoomIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllRoomInvitesByRoomIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllRoomInvitesByRoomIDResponse) GetInvites() []*RoomInvite {
	if x != nil {
		return x.Invites
	}
	return nil
}

type FindAllRoomInvitesByInviteToRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteTo string `protobuf:"bytes,1,opt,name=invite_to,json=inviteTo,proto3" json:"invite_to,omitempty"`
}

func (x *FindAllRoomInvitesByInviteToRequest) Reset() {
	*x = FindAllRoomInvitesByInviteToRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllRoomInvitesByInviteToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoomInvitesByInviteToRequest) ProtoMessage() {}

func (x *FindAllRoomInvitesByInviteToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoomInvitesByInviteToRequest.ProtoReflect.Descriptor instead.
func (*FindAllRoomInvitesByInviteToRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{9}
}

func (x *FindAllRoomInvitesByInviteToRequest) GetInviteTo() string {
	if x != nil {
		return x.InviteTo
	}
	return ""
}

type FindAllRoomInvitesByInviteToResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invites []*RoomInvite `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
}

func (x *FindAllRoomInvitesByInviteToResponse) Reset() {
	*x = FindAllRoomInvitesByInviteToResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllRoomInvitesByInviteToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoomInvitesByInviteToResponse) ProtoMessage() {}

func (x *FindAllRoomInvitesByInviteToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoomInvitesByInviteToResponse.ProtoReflect.Descriptor instead.
func (*FindAllRoomInvitesByInviteToResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{10}
}

func (x *FindAllRoomInvitesByInviteToResponse) GetInvites() []*RoomInvite {
	if x != nil {
		return x.Invites
	}
	return nil
}

type PatchRoomInviteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId     int32  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sender     string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	InviteTo   string `protobuf:"bytes,4,opt,name=invite_to,json=inviteTo,proto3" json:"invite_to,omitempty"`
	IsAccepted bool   `protobuf:"varint,5,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"`
	IsDenied   bool   `protobuf:"varint,6,opt,name=is_denied,json=isDenied,proto3" json:"is_denied,omitempty"`
}

func (x *PatchRoomInviteRequest) Reset() {
	*x = PatchRoomInviteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchRoomInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRoomInviteRequest) ProtoMessage() {}

func (x *PatchRoomInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRoomInviteRequest.ProtoReflect.Descriptor instead.
func (*PatchRoomInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{11}
}

func (x *PatchRoomInviteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchRoomInviteRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PatchRoomInviteRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PatchRoomInviteRequest) GetInviteTo() string {
	if x != nil {
		return x.InviteTo
	}
	return ""
}

func (x *PatchRoomInviteRequest) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *PatchRoomInviteRequest) GetIsDenied() bool {
	if x != nil {
		return x.IsDenied
	}
	return false
}

type PatchRoomInviteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invite *RoomInvite `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
}

func (x *PatchRoomInviteResponse) Reset() {
	*x = PatchRoomInviteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchRoomInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRoomInviteResponse) ProtoMessage() {}

func (x *PatchRoomInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRoomInviteResponse.ProtoReflect.Descriptor instead.
func (*PatchRoomInviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{12}
}

func (x *PatchRoomInviteResponse) GetInvite() *RoomInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

type DeleteRoomInviteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRoomInviteRequest) Reset() {
	*x = DeleteRoomInviteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomInviteRequest) ProtoMessage() {}

func (x *DeleteRoomInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomInviteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRoomInviteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoomInviteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteRoomInviteResponse) Reset() {
	*x = DeleteRoomInviteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomInviteResponse) ProtoMessage() {}

func (x *DeleteRoomInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomInviteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomInviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRoomInviteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AcceptedRoomInviteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AcceptedRoomInviteRequest) Reset() {
	*x = AcceptedRoomInviteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptedRoomInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedRoomInviteRequest) ProtoMessage() {}

func (x *AcceptedRoomInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedRoomInviteRequest.ProtoReflect.Descriptor instead.
func (*AcceptedRoomInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{15}
}

func (x *AcceptedRoomInviteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AcceptedRoomInviteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AcceptedRoomInviteResponse) Reset() {
	*x = AcceptedRoomInviteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_invite_room_invite_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptedRoomInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedRoomInviteResponse) ProtoMessage() {}

func (x *AcceptedRoomInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_invite_room_invite_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedRoomInviteResponse.ProtoReflect.Descriptor instead.
func (*AcceptedRoomInviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_invite_room_invite_proto_rawDescGZIP(), []int{16}
}

func (x *AcceptedRoomInviteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_room_invite_room_invite_proto protoreflect.FileDescriptor

var file_proto_room_invite_room_invite_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9e, 0x02, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x22, 0x4a, 0x0a, 0x18, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52,
	0x06, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x22, 0x2b, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x06, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x22, 0x3b, 0x0a, 0x21, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22,
	0x56, 0x0a, 0x22, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x07,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x21, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x22, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x22, 0x42, 0x0a,
	0x23, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x74,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54,
	0x6f, 0x22, 0x58, 0x0a, 0x24, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x16,
	0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x5f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x54, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6e, 0x69,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6e, 0x69,
	0x65, 0x64, 0x22, 0x49, 0x0a, 0x17, 0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x06, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x22, 0x29, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b,
	0x0a, 0x19, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x1a, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xf5, 0x06, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x23, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x25,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a,
	0x1a, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x73, 0x42, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x2d, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x1a, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73,
	0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x2d, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x12, 0x2f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x54, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x22,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e,
	0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_room_invite_room_invite_proto_rawDescOnce sync.Once
	file_proto_room_invite_room_invite_proto_rawDescData = file_proto_room_invite_room_invite_proto_rawDesc
)

func file_proto_room_invite_room_invite_proto_rawDescGZIP() []byte {
	file_proto_room_invite_room_invite_proto_rawDescOnce.Do(func() {
		file_proto_room_invite_room_invite_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_room_invite_room_invite_proto_rawDescData)
	})
	return file_proto_room_invite_room_invite_proto_rawDescData
}

var file_proto_room_invite_room_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_room_invite_room_invite_proto_goTypes = []interface{}{
	(*RoomInvite)(nil),                           // 0: roominvite.RoomInvite
	(*CreateRoomInviteRequest)(nil),              // 1: roominvite.CreateRoomInviteRequest
	(*CreateRoomInviteResponse)(nil),             // 2: roominvite.CreateRoomInviteResponse
	(*FindRoomInviteByIDRequest)(nil),            // 3: roominvite.FindRoomInviteByIDRequest
	(*FindRoomInviteByIDResponse)(nil),           // 4: roominvite.FindRoomInviteByIDResponse
	(*FindAllRoomInvitesBySenderRequest)(nil),    // 5: roominvite.FindAllRoomInvitesBySenderRequest
	(*FindAllRoomInvitesBySenderResponse)(nil),   // 6: roominvite.FindAllRoomInvitesBySenderResponse
	(*FindAllRoomInvitesByRoomIDRequest)(nil),    // 7: roominvite.FindAllRoomInvitesByRoomIDRequest
	(*FindAllRoomInvitesByRoomIDResponse)(nil),   // 8: roominvite.FindAllRoomInvitesByRoomIDResponse
	(*FindAllRoomInvitesByInviteToRequest)(nil),  // 9: roominvite.FindAllRoomInvitesByInviteToRequest
	(*FindAllRoomInvitesByInviteToResponse)(nil), // 10: roominvite.FindAllRoomInvitesByInviteToResponse
	(*PatchRoomInviteRequest)(nil),               // 11: roominvite.PatchRoomInviteRequest
	(*PatchRoomInviteResponse)(nil),              // 12: roominvite.PatchRoomInviteResponse
	(*DeleteRoomInviteRequest)(nil),              // 13: roominvite.DeleteRoomInviteRequest
	(*DeleteRoomInviteResponse)(nil),             // 14: roominvite.DeleteRoomInviteResponse
	(*AcceptedRoomInviteRequest)(nil),            // 15: roominvite.AcceptedRoomInviteRequest
	(*AcceptedRoomInviteResponse)(nil),           // 16: roominvite.AcceptedRoomInviteResponse
	(*timestamppb.Timestamp)(nil),                // 17: google.protobuf.Timestamp
}
var file_proto_room_invite_room_invite_proto_depIdxs = []int32{
	17, // 0: roominvite.RoomInvite.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: roominvite.RoomInvite.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: roominvite.CreateRoomInviteResponse.invite:type_name -> roominvite.RoomInvite
	0,  // 3: roominvite.FindRoomInviteByIDResponse.invite:type_name -> roominvite.RoomInvite
	0,  // 4: roominvite.FindAllRoomInvitesBySenderResponse.invites:type_name -> roominvite.RoomInvite
	0,  // 5: roominvite.FindAllRoomInvitesByRoomIDResponse.invites:type_name -> roominvite.RoomInvite
	0,  // 6: roominvite.FindAllRoomInvitesByInviteToResponse.invites:type_name -> roominvite.RoomInvite
	0,  // 7: roominvite.PatchRoomInviteResponse.invite:type_name -> roominvite.RoomInvite
	1,  // 8: roominvite.RoomInviteService.CreateRoomInvite:input_type -> roominvite.CreateRoomInviteRequest
	3,  // 9: roominvite.RoomInviteService.FindRoomInviteByID:input_type -> roominvite.FindRoomInviteByIDRequest
	5,  // 10: roominvite.RoomInviteService.FindAllRoomInvitesBySender:input_type -> roominvite.FindAllRoomInvitesBySenderRequest
	7,  // 11: roominvite.RoomInviteService.FindAllRoomInvitesByRoomID:input_type -> roominvite.FindAllRoomInvitesByRoomIDRequest
	9,  // 12: roominvite.RoomInviteService.FindAllRoomInvitesByInviteTo:input_type -> roominvite.FindAllRoomInvitesByInviteToRequest
	11, // 13: roominvite.RoomInviteService.PatchRoomInvite:input_type -> roominvite.PatchRoomInviteRequest
	13, // 14: roominvite.RoomInviteService.DeleteRoomInvite:input_type -> roominvite.DeleteRoomInviteRequest
	15, // 15: roominvite.RoomInviteService.AcceptedRoomInvite:input_type -> roominvite.AcceptedRoomInviteRequest
	2,  // 16: roominvite.RoomInviteService.CreateRoomInvite:output_type -> roominvite.CreateRoomInviteResponse
	4,  // 17: roominvite.RoomInviteService.FindRoomInviteByID:output_type -> roominvite.FindRoomInviteByIDResponse
	6,  // 18: roominvite.RoomInviteService.FindAllRoomInvitesBySender:output_type -> roominvite.FindAllRoomInvitesBySenderResponse
	8,  // 19: roominvite.RoomInviteService.FindAllRoomInvitesByRoomID:output_type -> roominvite.FindAllRoomInvitesByRoomIDResponse
	10, // 20: roominvite.RoomInviteService.FindAllRoomInvitesByInviteTo:output_type -> roominvite.FindAllRoomInvitesByInviteToResponse
	12, // 21: roominvite.RoomInviteService.PatchRoomInvite:output_type -> roominvite.PatchRoomInviteResponse
	14, // 22: roominvite.RoomInviteService.DeleteRoomInvite:output_type -> roominvite.DeleteRoomInviteResponse
	16, // 23: roominvite.RoomInviteService.AcceptedRoomInvite:output_type -> roominvite.AcceptedRoomInviteResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_room_invite_room_invite_proto_init() }
func file_proto_room_invite_room_invite_proto_init() {
	if File_proto_room_invite_room_invite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_room_invite_room_invite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomInviteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomInviteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRoomInviteByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRoomInviteByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllRoomInvitesBySenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllRoomInvitesBySenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllRoomInvitesByRoomIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllRoomInvitesByRoomIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllRoomInvitesByInviteToRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllRoomInvitesByInviteToResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchRoomInviteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchRoomInviteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomInviteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomInviteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptedRoomInviteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_invite_room_invite_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptedRoomInviteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_room_invite_room_invite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_invite_room_invite_proto_goTypes,
		DependencyIndexes: file_proto_room_invite_room_invite_proto_depIdxs,
		MessageInfos:      file_proto_room_invite_room_invite_proto_msgTypes,
	}.Build()
	File_proto_room_invite_room_invite_proto = out.File
	file_proto_room_invite_room_invite_proto_rawDesc = nil
	file_proto_room_invite_room_invite_proto_goTypes = nil
	file_proto_room_invite_room_invite_proto_depIdxs = nil
}
