// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: proto/room_member/room_member.proto

package room_member

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chatroom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomName  string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	IsGroup   bool                   `protobuf:"varint,3,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	Owner     string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Chatroom) Reset() {
	*x = Chatroom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chatroom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chatroom) ProtoMessage() {}

func (x *Chatroom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chatroom.ProtoReflect.Descriptor instead.
func (*Chatroom) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{0}
}

func (x *Chatroom) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chatroom) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *Chatroom) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *Chatroom) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Chatroom) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chatroom) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId    int32                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId    string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Chatroom  *Chatroom              `protobuf:"bytes,4,opt,name=chatroom,proto3" json:"chatroom,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *RoomMember) Reset() {
	*x = RoomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMember) ProtoMessage() {}

func (x *RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMember.ProtoReflect.Descriptor instead.
func (*RoomMember) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{1}
}

func (x *RoomMember) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomMember) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomMember) GetChatroom() *Chatroom {
	if x != nil {
		return x.Chatroom
	}
	return nil
}

func (x *RoomMember) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomMember) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRoomMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  int32    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *CreateRoomMembersRequest) Reset() {
	*x = CreateRoomMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomMembersRequest) ProtoMessage() {}

func (x *CreateRoomMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomMembersRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomMembersRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoomMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CreateRoomMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*RoomMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *CreateRoomMembersResponse) Reset() {
	*x = CreateRoomMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomMembersResponse) ProtoMessage() {}

func (x *CreateRoomMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomMembersResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomMembersResponse) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type FindAllByRoomIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *FindAllByRoomIDRequest) Reset() {
	*x = FindAllByRoomIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByRoomIDRequest) ProtoMessage() {}

func (x *FindAllByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllByRoomIDRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type FindAllByRoomIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*RoomMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *FindAllByRoomIDResponse) Reset() {
	*x = FindAllByRoomIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByRoomIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByRoomIDResponse) ProtoMessage() {}

func (x *FindAllByRoomIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByRoomIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllByRoomIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllByRoomIDResponse) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type FindAllByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FindAllByUserIDRequest) Reset() {
	*x = FindAllByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserIDRequest) ProtoMessage() {}

func (x *FindAllByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindAllByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chatrooms []*RoomMember `protobuf:"bytes,1,rep,name=chatrooms,proto3" json:"chatrooms,omitempty"`
}

func (x *FindAllByUserIDResponse) Reset() {
	*x = FindAllByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserIDResponse) ProtoMessage() {}

func (x *FindAllByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllByUserIDResponse) GetChatrooms() []*RoomMember {
	if x != nil {
		return x.Chatrooms
	}
	return nil
}

type FindByRoomIDAndUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FindByRoomIDAndUserIDRequest) Reset() {
	*x = FindByRoomIDAndUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByRoomIDAndUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByRoomIDAndUserIDRequest) ProtoMessage() {}

func (x *FindByRoomIDAndUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByRoomIDAndUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindByRoomIDAndUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{8}
}

func (x *FindByRoomIDAndUserIDRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *FindByRoomIDAndUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindByRoomIDAndUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *RoomMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *FindByRoomIDAndUserIDResponse) Reset() {
	*x = FindByRoomIDAndUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByRoomIDAndUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByRoomIDAndUserIDResponse) ProtoMessage() {}

func (x *FindByRoomIDAndUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByRoomIDAndUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindByRoomIDAndUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{9}
}

func (x *FindByRoomIDAndUserIDResponse) GetMember() *RoomMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type DeleteByRoomIDAndUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeleteByRoomIDAndUserIDRequest) Reset() {
	*x = DeleteByRoomIDAndUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteByRoomIDAndUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByRoomIDAndUserIDRequest) ProtoMessage() {}

func (x *DeleteByRoomIDAndUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByRoomIDAndUserIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteByRoomIDAndUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteByRoomIDAndUserIDRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *DeleteByRoomIDAndUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteByRoomIDAndUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteByRoomIDAndUserIDResponse) Reset() {
	*x = DeleteByRoomIDAndUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteByRoomIDAndUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByRoomIDAndUserIDResponse) ProtoMessage() {}

func (x *DeleteByRoomIDAndUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByRoomIDAndUserIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteByRoomIDAndUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteByRoomIDAndUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAllByRoomIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *DeleteAllByRoomIDRequest) Reset() {
	*x = DeleteAllByRoomIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAllByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllByRoomIDRequest) ProtoMessage() {}

func (x *DeleteAllByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAllByRoomIDRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DeleteAllByRoomIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteAllByRoomIDResponse) Reset() {
	*x = DeleteAllByRoomIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAllByRoomIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllByRoomIDResponse) ProtoMessage() {}

func (x *DeleteAllByRoomIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllByRoomIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteAllByRoomIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAllByRoomIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRoomMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRoomMemberRequest) Reset() {
	*x = DeleteRoomMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomMemberRequest) ProtoMessage() {}

func (x *DeleteRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRoomMemberRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoomMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteRoomMemberResponse) Reset() {
	*x = DeleteRoomMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_member_room_member_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomMemberResponse) ProtoMessage() {}

func (x *DeleteRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_member_room_member_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_member_room_member_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRoomMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_room_member_room_member_proto protoreflect.FileDescriptor

var file_proto_room_member_room_member_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x69, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0xf6, 0x01, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x08, 0x63, 0x68,
	0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4e, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x19,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x4b,
	0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4f,
	0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x63, 0x68, 0x61,
	0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x09, 0x63, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22,
	0x50, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x41,
	0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x4f, 0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x52, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c,
	0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0xd0, 0x05, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x22, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6c, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x28, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x41, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x42,
	0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x24, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x42, 0x79,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_room_member_room_member_proto_rawDescOnce sync.Once
	file_proto_room_member_room_member_proto_rawDescData = file_proto_room_member_room_member_proto_rawDesc
)

func file_proto_room_member_room_member_proto_rawDescGZIP() []byte {
	file_proto_room_member_room_member_proto_rawDescOnce.Do(func() {
		file_proto_room_member_room_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_room_member_room_member_proto_rawDescData)
	})
	return file_proto_room_member_room_member_proto_rawDescData
}

var file_proto_room_member_room_member_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_room_member_room_member_proto_goTypes = []interface{}{
	(*Chatroom)(nil),                        // 0: roommember.Chatroom
	(*RoomMember)(nil),                      // 1: roommember.RoomMember
	(*CreateRoomMembersRequest)(nil),        // 2: roommember.CreateRoomMembersRequest
	(*CreateRoomMembersResponse)(nil),       // 3: roommember.CreateRoomMembersResponse
	(*FindAllByRoomIDRequest)(nil),          // 4: roommember.FindAllByRoomIDRequest
	(*FindAllByRoomIDResponse)(nil),         // 5: roommember.FindAllByRoomIDResponse
	(*FindAllByUserIDRequest)(nil),          // 6: roommember.FindAllByUserIDRequest
	(*FindAllByUserIDResponse)(nil),         // 7: roommember.FindAllByUserIDResponse
	(*FindByRoomIDAndUserIDRequest)(nil),    // 8: roommember.FindByRoomIDAndUserIDRequest
	(*FindByRoomIDAndUserIDResponse)(nil),   // 9: roommember.FindByRoomIDAndUserIDResponse
	(*DeleteByRoomIDAndUserIDRequest)(nil),  // 10: roommember.DeleteByRoomIDAndUserIDRequest
	(*DeleteByRoomIDAndUserIDResponse)(nil), // 11: roommember.DeleteByRoomIDAndUserIDResponse
	(*DeleteAllByRoomIDRequest)(nil),        // 12: roommember.DeleteAllByRoomIDRequest
	(*DeleteAllByRoomIDResponse)(nil),       // 13: roommember.DeleteAllByRoomIDResponse
	(*DeleteRoomMemberRequest)(nil),         // 14: roommember.DeleteRoomMemberRequest
	(*DeleteRoomMemberResponse)(nil),        // 15: roommember.DeleteRoomMemberResponse
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
}
var file_proto_room_member_room_member_proto_depIdxs = []int32{
	16, // 0: roommember.Chatroom.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: roommember.Chatroom.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: roommember.RoomMember.chatroom:type_name -> roommember.Chatroom
	16, // 3: roommember.RoomMember.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: roommember.RoomMember.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: roommember.CreateRoomMembersResponse.members:type_name -> roommember.RoomMember
	1,  // 6: roommember.FindAllByRoomIDResponse.members:type_name -> roommember.RoomMember
	1,  // 7: roommember.FindAllByUserIDResponse.chatrooms:type_name -> roommember.RoomMember
	1,  // 8: roommember.FindByRoomIDAndUserIDResponse.member:type_name -> roommember.RoomMember
	2,  // 9: roommember.RoomMemberService.CreateRoomMembers:input_type -> roommember.CreateRoomMembersRequest
	4,  // 10: roommember.RoomMemberService.FindAllByRoomID:input_type -> roommember.FindAllByRoomIDRequest
	6,  // 11: roommember.RoomMemberService.FindAllByUserID:input_type -> roommember.FindAllByUserIDRequest
	8,  // 12: roommember.RoomMemberService.FindByRoomIDAndUserID:input_type -> roommember.FindByRoomIDAndUserIDRequest
	10, // 13: roommember.RoomMemberService.DeleteByRoomIDAndUserID:input_type -> roommember.DeleteByRoomIDAndUserIDRequest
	12, // 14: roommember.RoomMemberService.DeleteAllByRoomID:input_type -> roommember.DeleteAllByRoomIDRequest
	14, // 15: roommember.RoomMemberService.DeleteRoomMember:input_type -> roommember.DeleteRoomMemberRequest
	3,  // 16: roommember.RoomMemberService.CreateRoomMembers:output_type -> roommember.CreateRoomMembersResponse
	5,  // 17: roommember.RoomMemberService.FindAllByRoomID:output_type -> roommember.FindAllByRoomIDResponse
	7,  // 18: roommember.RoomMemberService.FindAllByUserID:output_type -> roommember.FindAllByUserIDResponse
	9,  // 19: roommember.RoomMemberService.FindByRoomIDAndUserID:output_type -> roommember.FindByRoomIDAndUserIDResponse
	11, // 20: roommember.RoomMemberService.DeleteByRoomIDAndUserID:output_type -> roommember.DeleteByRoomIDAndUserIDResponse
	13, // 21: roommember.RoomMemberService.DeleteAllByRoomID:output_type -> roommember.DeleteAllByRoomIDResponse
	15, // 22: roommember.RoomMemberService.DeleteRoomMember:output_type -> roommember.DeleteRoomMemberResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_room_member_room_member_proto_init() }
func file_proto_room_member_room_member_proto_init() {
	if File_proto_room_member_room_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_room_member_room_member_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chatroom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByRoomIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByRoomIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByRoomIDAndUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByRoomIDAndUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteByRoomIDAndUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteByRoomIDAndUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAllByRoomIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAllByRoomIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_member_room_member_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_room_member_room_member_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_member_room_member_proto_goTypes,
		DependencyIndexes: file_proto_room_member_room_member_proto_depIdxs,
		MessageInfos:      file_proto_room_member_room_member_proto_msgTypes,
	}.Build()
	File_proto_room_member_room_member_proto = out.File
	file_proto_room_member_room_member_proto_rawDesc = nil
	file_proto_room_member_room_member_proto_goTypes = nil
	file_proto_room_member_room_member_proto_depIdxs = nil
}
